### ISSUE TITLE
MaterialXMaya fails to compile due to UDIM changes

### ISSUE THREAD

**Issue by ppenenko** [autodesk-forks/MaterialX#653]
error C2039: 'getUdimPaths': is not a member of 'MaterialX'
error C3861: 'getUdimPaths': identifier not found

Apparently a regression from https://github.com/autodesk-forks/MaterialX/pull/649/files#diff-8097f8933aaf4d5463873ae9a6cdb199L732

**Comment by jstone-lucasfilm** [comment]
Would it be possible to use a StringResolver instead of this helper function?  That’s the approach now used in MaterialXView, and it supports UDIM string replacement in addition to other types of string substitutions.

**Comment by ppenenko** [comment]
Sure, that's what I'm planning to do. We simply forgot to update the plugin because it's not covered by CI here.
